### ISSUE TITLE
Massive slow down all of a sudden

### ISSUE THREAD

**Issue by dylaniti** [telerik/figma-instarelinker-community#1]
Hello, love the plugin, use it all the time!

All of a sudden today, when I would run the plugin for multiple components it would not work. It will just spin forever. However, one at a time does work

Any suggestions/fixes? Thanks!

**Comment by atanasovg** [comment]
Hello,

Thank you for the feedback - really glad you like the plugin!

Not sure what is causing this unexpected behavior. Some questions to help me better understand the case:

- When the plugin spins forever is the rest of the document/UI responsive or blocked?
- What is the toast information by the plugin? It prompts for every operation it starts.
- Could you check for exceptions in the Figma development console? You can open the console by clicking the 
   Plugins->Development->Open Console 
   command in the menu

Also, it would help a lot if you can isolate the behavior in a demo Figma file so that I can reproduce and debug locally.

Thanks,
Looking forward to resolve this

**Comment by dylaniti** [comment]
Thanks for the response!


**When the plugin spins forever is the rest of the document/UI responsive or blocked?**
The document and UI works normally while it is spinning.

**What is the toast information by the plugin? It prompts for every operation it starts.**
"Finding remote components and styles in the selection. This might take a while, please wait." Then it spins.

**Could you check for exceptions in the Figma development console?**
![instarelinker-figma-console](https://user-images.githubusercontent.com/99846086/154582427-d674db28-3640-4589-83b4-61d62cf5e0fe.png)

I tried recreating this issue in the same type of way, but cannot seem to do it. It seems to work in other files, just not this one. Unfortunately, I cannot share this file but I can provide more context if needed.

Thanks so much for looking into this!

**Comment by matko13** [comment]
> Thanks for the response!
> 
> **When the plugin spins forever is the rest of the document/UI responsive or blocked?** The document and UI works normally while it is spinning.
> 
> **What is the toast information by the plugin? It prompts for every operation it starts.** "Finding remote components and styles in the selection. This might take a while, please wait." Then it spins.
> 
> **Could you check for exceptions in the Figma development console?** ![instarelinker-figma-console](https://user-images.githubusercontent.com/99846086/154582427-d674db28-3640-4589-83b4-61d62cf5e0fe.png)
> 
> I tried recreating this issue in the same type of way, but cannot seem to do it. It seems to work in other files, just not this one. Unfortunately, I cannot share this file but I can provide more context if needed.
> 
> Thanks so much for looking into this!

I have exactly the same issue!

**Comment by atanasovg** [comment]
Thank you for the additional information - it is a bug as seen in the console - something is null when it is not expected to be. I will try to isolate locally and will double check the code. Once we fix this we will upload a new plugin version on the community.

**Comment by matko13** [comment]
thanks @atanasovg, when you fix this, you can also give a shout here as well.

**Comment by atanasovg** [comment]
@dylaniti @matko13 
Hi guys, we just published a new version on the community with a fix for this bug. I couldn't reproduce the behavior locally, so the fix is kind of blind. The API call
```
figma.getStyleById
```
returns null and my guess is that this may happen when an access to a remote component is not available.
In such cases the plugin will not crash but it will not be able to do anything with the style(s).

Let me know how it goes.

**Comment by dylaniti** [comment]
Hello atanasovg, thanks so much for being so quick about this!

I just tested this on the file that was giving me issues and it worked! The only thing that was kind of weird was that it spun forever on the last step "Running Instarelinker" but I just pressed the "X" button, and everything worked fine.

Thanks again for fixing this, you saved my workflow!

**Comment by matko13** [comment]
Hey, it still doesn't work for me 
<img width="310" alt="image" src="https://user-images.githubusercontent.com/528776/161597970-be568aa5-b51f-4c7c-97c5-b1143d61205f.png">

I'm trying to get remote styles and replace them with local ones. I have an access to the file with remote styles.
